DIFFICULTY_LEVEL_BEGINNER = 0
DIFFICULTY_LEVEL_INTERMEDIATE = 1
DIFFICULTY_LEVEL_ADVANCED = 2

DIFFICULTY_LEVEL_BEGINNER_STR = "Beginner"
DIFFICULTY_LEVEL_INTERMEDIATE_STR = "Intermediate"
DIFFICULTY_LEVEL_ADVANCED_STR = "Advanced"

COST_FREE = 0
COST_PAID = 1

COST_FREE_STR = "Free"
COST_PAID_STR = "Paid"
